# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.7.1/c2cciutils/schema.json

publish:
  pypi:
    packages: []
  docker:
    dispatch: {}
    images:
      - name: camptocamp/nominatim
        tags:
          - '{version}'

version:
  branch_to_version_re:
    - from: ([0-9]+.[0-9]+.[0-9]+)
      to: \1
    - from: master
      to: master
