name: Rebuild

on:
  schedule:
    - cron: 30 2 * * *

jobs:
  rebuild:
    name: Rebuild
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '4.4.0'

    steps:
      - run: docker system prune --all --force
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker
        if: github.repository == 'camptocamp/docker-nominatim'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - run: make build
      - run: make acceptance
      - run: (cd acceptance_tests && (c2cciutils-docker-logs || docker-compose logs))
        if: always()

      - name: Publish
        run: c2cciutils-publish --type=rebuild --branch=${{ matrix.branch }}
